name = "HorizonSideFix"
uuid = "e3906e16-c448-40e5-b774-923606885f02"
authors = ["strikeDusha from mirea with love <3"]
version = "0.3.1"

[deps]
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"

[compat]
julia = "1"
PyPlot = "2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
